sudo: required
services:
  - docker

before_install:
  - docker build -t pinaevnikita/docker-react -f Dockerfile.dev .

script:
  - docker run pinaevnikita/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "somename"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_ACCESS_KEY"